### ISSUE TITLE
Wrong Assumption of Date Format

### ISSUE THREAD

**Issue by bhamodi** [vikstrous/Quest-Schedule-Exporter#9]
Hello there,

I've encountered a small bug when I tried exporting my schedule. It was incorrectly swapping my month and day causing my events to be incorrectly placed on google calendar.

Specifically, my start date was 01-05-2015, but instead of reading that as January 5th, 2015, it read it as May 1st, 2015. I suspect that this issue was caused by PR #4.

**Comment by bhamodi** [comment]
@vikstrous @johnwyz88

**Comment by vikstrous** [comment]
Please report issues here: https://github.com/VVCepheiA/Quest-Schedule-Exporter

**Comment by bhamodi** [comment]
I am unable to create an issue against that repo as it just a fork of this one. I only have the option to submit a pull request. The `New issue` button isn't available.

**Comment by vikstrous** [comment]
Hmm, yeah, I just noticed that. @VVCepheiA please look into this.

**Comment by bhamodi** [comment]
New way to download Quest schedule: https://chrome.google.com/webstore/detail/uwaterloo-schedule-export/epamhdpboimbcdgokgldffcdkfmbmajg

Open-sourced at: https://github.com/bhamodi/uwaterloo-schedule-exporter
